//MOVIES
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";
export const FILTER_MOVIES = "FILTER_MOVIES";

//USER
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_FAILED = "AUTH_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_UPDATED = "USER_UPDATED";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";

//SYSTEM MESSAGES
export const ADD_MESSAGE = "ADD_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const MESSAGE_RENDERED = "MESSAGE_RENDERED";
